export { default as AvatarYellow } from './avatarYellow'
export { default as AvatarGreen } from './avatarGreen'
export { default as AvatarGreenYellow } from './avatarGreenYellow'
export { default as avatarGreenBlue } from './avatarGreenBlue'
export { default as avatarRedOrange } from './avatarRedOrange'
